/**
 * Union of permission names — mirrors spring-boilerplate's `UserPermission`
 * enum exactly. The backend enum is the single source of truth; keep in sync.
 */
export type UserPermission =
  | 'TENANT_READ'
  | 'TENANT_CREATE'
  | 'TENANT_UPDATE'
  | 'TENANT_DELETE'
  | 'USER_READ'
  | 'USER_WRITE'
  | 'USER_CREATE'
  | 'USER_UPDATE'
  | 'USER_DELETE'
  | 'USER_ENABLE'
  | 'USER_ASSIGN_ROLE'
  | 'ROLE_READ'
  | 'ROLE_WRITE'
  | 'ROLE_DELETE'
  | 'ROLE_ASSIGN_PERMISSION'
  | 'DEPARTMENT_READ'
  | 'DEPARTMENT_CREATE'
  | 'DEPARTMENT_UPDATE'
  | 'DEPARTMENT_DELETE'
  | 'EXPENSE_READ'
  | 'EXPENSE_READ_ALL'
  | 'EXPENSE_CREATE'
  | 'EXPENSE_UPDATE'
  | 'EXPENSE_DELETE'
  | 'EXPENSE_APPROVE'
  | 'EXPENSE_REJECT'
  | 'EXPENSE_PROCESS'
  | 'MFA_MANAGE'
  | 'REPORT_READ'
  | 'AUDIT_LOG_READ'
