// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/21/2026, 6:48:03 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/runner/work/nuxt-boilerplate/nuxt-boilerplate/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/nuxt-boilerplate/nuxt-boilerplate/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/nuxt-boilerplate/nuxt-boilerplate/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/nuxt-boilerplate/nuxt-boilerplate/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/nuxt-boilerplate/nuxt-boilerplate/plugins/**/*.{js,ts,mjs}","/home/runner/work/nuxt-boilerplate/nuxt-boilerplate/composables/**/*.{js,ts,mjs}","/home/runner/work/nuxt-boilerplate/nuxt-boilerplate/utils/**/*.{js,ts,mjs}","/home/runner/work/nuxt-boilerplate/nuxt-boilerplate/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/nuxt-boilerplate/nuxt-boilerplate/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/nuxt-boilerplate/nuxt-boilerplate/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/runner/work/nuxt-boilerplate/nuxt-boilerplate/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;